### ISSUE TITLE
Add Instructions for using ValidatableProtocol

### ISSUE THREAD

**Issue by davepatterson** [jpotts18/SwiftValidator#120]
In readme add a few lines showing how users should ValidatableProtocol.

**Comment by dadalar** [comment]
Also, some delegate method parameter types are changed. Readme file should be updated accordingly. Since this breaks 3.x versions, I suggest giving new version 4.0

`func validationFailed(errors:[UITextField:ValidationError])`
is now tuple: 
`func validationFailed(errors: [(Validatable, ValidationError)])`

**Comment by davepatterson** [comment]
Is fixed in #124 and previous readMe edits that I have done.
