### ISSUE TITLE
PhoneNumberValidator not public

### ISSUE THREAD

**Issue by ir-tech** [jpotts18/SwiftValidator#55]
Hello, I'm currently using this cool librairy but found something which seems strange to me.

There is a working PhoneNumber-Validator, but it's not usable rightnow because the class is not marked as public. I changed it locally, but maybe this should be fixed on your side, otherwhise the next release will overwrite my changes.

Greetings

**Comment by jonah-williams** [comment]
I was just looking at this. I suspect the existing phone number rule has been excluded because it is too simplistic (it looks for a 10 digit string). As a result it only works in some countries, for non-international numbers, and requires preprocessing to strip dashes, parens, spaces, and any other characters users might reasonably enter into a phone number input.

A more complete rule might leverage https://github.com/iziz/libPhoneNumber-iOS but I don't know if it's worthwhile to add a dependency to SwiftValidator. Maybe phone number validation should be a subspec to make including it optional?

What do you think @jpotts18?

**Comment by jpotts18** [comment]
I would recommend extending the RegexRule and creating whatever phone number validation you need. I don't really want to bloat this library by adding all potential cases found in the libPhoneNumber-iOS library.
